### ISSUE TITLE
using https instead of http

### ISSUE THREAD

**Issue by basox70** [Jason-Bloomer/DUOpenMarket#1]
Hi,
You made an API, that's a nice thing you thought about
The only thing I would suggest you is to stop using http and use https instead.
It's easy nowadays with website like "Let's Encrypt"

If you need help, feel free to message me on discord (Basox70#0001)

**Comment by Jason-Bloomer** [comment]
Previously the project was using .NET Framework Version 4.2, which lacks support for TLS 1.3.
My server provider, only provides TLS 1.3 certs... so without the support, I was unable to change this.
I have only recently set the project to target version 4.8 with the required TLS 1.3 support.

You should see this corrected in revision 0.43.1+.
