### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by EliteOperation** [Jason-Bloomer/DUOpenMarket#3]
![grafik](https://user-images.githubusercontent.com/116909139/198694699-14d0bc2b-4408-4f24-b875-e34d0cce1282.png)
10 sek after start, i get only errors 500.

**Comment by Jason-Bloomer** [comment]
Not a bug, working as intended. This is noted in patch notes, as well as on Discord. These do not impact the functionality of the program. It's just feedback from the server.
